added back docker tests.

diff --git a/.github/workflows/metro_vision_ai_app_recipe_sanity.yaml b/.github/workflows/metro_vision_ai_app_recipe_sanity.yaml
--- a/.github/workflows/metro_vision_ai_app_recipe_sanity.yaml
+++ b/.github/workflows/metro_vision_ai_app_recipe_sanity.yaml
@@ -73,7 +73,31 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y python3-nose libxml2-utils vlc
-      
+      - name: Sanity Test
+        run: |
+          sudo apt-get update
+          sudo pip install --ignore-installed robotframework
+          lspci | grep -i vga
+          
+          sudo pip install --ignore-installed selenium 
+          sudo pip install --ignore-installed  PyYAML
+          cd edge-ai-suites-repo/metro-ai-suite/metro-vision-ai-app-recipe/test-suite/robot_files
+          robot test.robot || true  &
+          sleep 480
+          docker logs dlstreamer-pipeline-server >> dlsps_logs.txt &
+          wait
+          mkdir -p /tmp/test_results
+          cp -r report.html log.html output.xml dlsps_logs.txt /tmp/test_results/
+          passed=$(xmllint --xpath "//return/status[@status='PASS']" ./output.xml | wc -l) || true
+          failed=$(xmllint --xpath "//return/status[@status='FAIL']" ./output.xml | wc -l) || true
+          not_run=$(xmllint --xpath "//return/status[@status='NOT RUN']" ./output.xml | wc -l) || true
+          total=$((passed + failed + not_run))
+          echo "### Sanity Test Summary" >> $GITHUB_STEP_SUMMARY
+          echo "- Total: $total" >> $GITHUB_STEP_SUMMARY
+          echo "- ✅ Passed: $passed" >> $GITHUB_STEP_SUMMARY
+          echo "- ❌ Failed: $failed" >> $GITHUB_STEP_SUMMARY
+          echo "- ⏭️ Not Run: $not_run" >> $GITHUB_STEP_SUMMARY
+          echo "- 📄 [Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
       - name: Helm Sanity Test
         run: |
           
